"use client";

import { useState, useEffect } from 'react';
import { useBookStore, useCurrentProject } from '@/lib/store';
import { Button } from '@/components/ui/button';
import { Loader2, Sparkles, ArrowRight, ArrowLeft, BookOpen, PenTool, LayoutTemplate, Rotate3d, AlignLeft, Info, Palette, Type, ArrowUpToLine, AlignVerticalJustifyCenter, ArrowDownToLine } from 'lucide-react';
import ProgressStepper from '@/components/ProgressStepper';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';

export default function DesignPage() {
    const { data: session, status } = useSession();
    const router = useRouter();
    const currentProject = useCurrentProject();
    const { setCoverDesign } = useBookStore();

    const [isGenerating, setIsGenerating] = useState(false);
    const [isImageLoading, setIsImageLoading] = useState(false); // To track the actual image load
    const [isSuggesting, setIsSuggesting] = useState(false);
    const [bgImageUrl, setBgImageUrl] = useState<string | null>(null);

    // User Input State
    const [formData, setFormData] = useState({
        concept: '',
        frontDesc: '',
        spineDesc: '',
        backDesc: ''
    });

    // 3D Viewer State
    const [viewAngle, setViewAngle] = useState<'front' | 'spine' | 'back' | 'perspective'>('perspective');

    // Typography and Layout State (Overrides AI)
    const [fontStyle, setFontStyle] = useState<'sans' | 'serif' | 'classic'>('serif');
    const [textPosition, setTextPosition] = useState<'top' | 'center' | 'bottom'>('center');

    // Design generated by AI
    const [designParams, setDesignParams] = useState<any>(currentProject?.coverDesign?.params || null);

    // Initialize bgImageUrl if present in saved params
    useEffect(() => {
        if (designParams?.imagePrompt && !bgImageUrl) {
            setBgImageUrl(`https://image.pollinations.ai/prompt/${encodeURIComponent(designParams.imagePrompt)}?width=800&height=1200&nologo=true`);
        }
    }, [designParams, bgImageUrl]);

    // Redirect if not authenticated
    useEffect(() => {
        if (status === 'unauthenticated') router.push('/login');
    }, [status, router]);

    // Redirect if no project selected
    useEffect(() => {
        if (status === 'authenticated' && !currentProject) router.push('/dashboard');
    }, [currentProject, status, router]);

    if (status === 'loading' || !session || !currentProject) {
        return (
            <div className="min-h-screen bg-[#faf9f6] flex items-center justify-center">
                <Loader2 className="animate-spin text-emerald-500 w-8 h-8" />
            </div>
        );
    }

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleGenerate = async () => {
        setIsGenerating(true);
        setViewAngle('perspective');
        try {
            const res = await fetch('/api/image', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    title: currentProject.title,
                    author: currentProject.author,
                    ...formData
                })
            });
            const data = await res.json();
            if (data.designParams) {
                setDesignParams(data.designParams);
                setCoverDesign({ params: data.designParams });

                if (data.designParams.imagePrompt) {
                    setIsImageLoading(true);
                    const promptText = data.designParams.imagePrompt;
                    const encodedPrompt = encodeURIComponent(promptText);
                    const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=800&height=1200&nologo=true`;

                    // Pre-load the image so it doesn't pop in
                    const img = new Image();
                    img.src = imageUrl;
                    img.onload = () => {
                        setBgImageUrl(imageUrl);
                        setIsImageLoading(false);
                    };
                    img.onerror = () => {
                        console.error("Image loading failed");
                        setIsImageLoading(false);
                        alert("배경 이미지 생성에 실패했습니다. 하지만 디자인 구성 요소는 적용되었습니다.");
                    };
                }
            } else if (data.error) {
                alert(`디자인 생성 실패: ${data.error}`);
            }
        } catch (error) {
            console.error(error);
            alert("디자인 생성 중 오류가 발생했습니다. 잠시 후 다시 시도해 주세요.");
        } finally {
            if (!isImageLoading) {
                setIsGenerating(false);
            }
        }
    };

    const handleSuggest = async () => {
        if (!currentProject?.fullDraft) {
            alert("원고 내용이 부족하여 추천을 받기 어렵습니다. 인터뷰를 조금 더 진행하거나 원고를 작성해 주세요.");
            return;
        }
        setIsSuggesting(true);
        try {
            const res = await fetch('/api/suggest-cover', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    title: currentProject.title,
                    author: currentProject.author,
                    content: currentProject.fullDraft
                })
            });
            const data = await res.json();
            if (data.suggestions) {
                setFormData({
                    concept: data.suggestions.concept || '',
                    frontDesc: data.suggestions.frontDesc || '',
                    spineDesc: data.suggestions.spineDesc || '',
                    backDesc: data.suggestions.backDesc || ''
                });
            } else if (data.error) {
                alert(`에코 추천 실패: ${data.error}`);
            }
        } catch (error) {
            console.error("Error fetching suggestions:", error);
            alert("추천을 받아오는데 실패했습니다. 잠시 후 다시 시도해 주세요.");
        } finally {
            setIsSuggesting(false);
        }
    };

    // --- 3D Rotation Logic ---
    let rotateY = -15;
    let rotateX = 5;
    let translateZ = 0;
    let scale = 1;

    switch (viewAngle) {
        case 'front': rotateY = 0; rotateX = 0; scale = 1.1; break;
        case 'spine': rotateY = 85; rotateX = 0; translateZ = -100; scale = 1.2; break;
        case 'back': rotateY = 180; rotateX = 0; scale = 1.1; break;
        case 'perspective': rotateY = -25; rotateX = 10; translateZ = -50; scale = 0.9; break;
    }

    // --- Default Design Fallback ---
    const design = designParams || {
        colors: { primary: '#064e3b', secondary: '#022c22', accent: '#fbbf24', textFront: '#ecfdf5', textSpine: '#ecfdf5' },
        style: { texture: 'leather', layout: 'elegant' },
        generatedTexts: { frontSubtitle: "A story waiting to be told...", backBlurb: "질문 폼을 채워나눔으로써 세상에 하나뿐인 나만의 표지를 디자인해보세요. 에코는 당신의 이야기에 가장 잘 어울리는 색상과 텍스처를 찾아낼 것입니다.", spineTitle: currentProject.title }
    };

    const { colors, style, generatedTexts } = design;

    const textureUrl = style.texture === 'leather'
        ? 'url("https://www.transparenttextures.com/patterns/leather.png")'
        : style.texture === 'canvas'
            ? 'url("https://www.transparenttextures.com/patterns/cream-paper.png")'
            : 'none';

    return (
        <div className="min-h-screen bg-[#FAFAFA] flex flex-col font-sans">
            <ProgressStepper />
            <header className="p-4 md:p-6 border-b bg-white flex flex-col sm:flex-row justify-between items-start sm:items-center sticky top-0 z-50 shadow-sm gap-3">
                <div>
                    <h1 className="text-xl md:text-2xl font-serif font-bold text-slate-800">3D 표지 렌더링</h1>
                    <p className="text-xs text-slate-400">에코(AI)와 함께 입체적인 표지를 디자인합니다.</p>
                </div>
                <div className="flex gap-2 w-full sm:w-auto">
                    <Button variant="outline" size="sm" onClick={() => router.push('/editor')} className="flex-1 sm:flex-none">
                        <ArrowLeft className="mr-1 h-4 w-4" /> 원고 교정
                    </Button>
                    <Button size="sm" onClick={() => router.push('/export')} className="flex-1 sm:flex-none bg-emerald-700 hover:bg-emerald-800 text-white shadow-md">
                        출판 및 배포 <ArrowRight className="ml-1 h-4 w-4" />
                    </Button>
                </div>
            </header>

            <main className="flex-1 max-w-[1600px] mx-auto w-full p-4 md:p-8 flex flex-col lg:flex-row gap-6 lg:gap-8">

                {/* Left: Input Form */}
                <aside className="w-full lg:w-[450px] flex flex-col gap-6 shrink-0 lg:h-[calc(100vh-140px)] lg:overflow-y-auto pr-0 lg:pr-2 pb-8 scrollbar-hide">
                    <div className="bg-white rounded-3xl p-6 shadow-xl shadow-emerald-900/5 border border-emerald-100">
                        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-slate-100">
                            <div className="w-10 h-10 rounded-full bg-emerald-100 flex items-center justify-center">
                                <Sparkles className="text-emerald-600 h-5 w-5" />
                            </div>
                            <div>
                                <h2 className="text-lg font-bold text-slate-800 break-keep">AI 커버 디자이너, 에코</h2>
                                <p className="text-sm text-slate-500 font-medium break-keep">원하시는 책의 느낌을 알려주세요.</p>
                            </div>
                        </div>

                        <Button
                            onClick={handleSuggest}
                            disabled={isSuggesting || isGenerating}
                            className="w-full mb-6 bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 rounded-xl py-6 font-bold text-sm sm:text-base shadow-sm hover:shadow transition-all group relative overflow-hidden"
                            variant="outline"
                        >
                            <div className="absolute inset-0 bg-gradient-to-r from-emerald-100/0 via-emerald-100/30 to-emerald-100/0 -translate-x-full group-hover:translate-x-full transition-transform duration-1000 ease-in-out"></div>
                            {isSuggesting ? (
                                <><Loader2 className="animate-spin mr-2 h-5 w-5" /> 에코가 원고를 읽고 아이디어를 떠올리는 중...</>
                            ) : (
                                <><Sparkles className="mr-2 h-5 w-5 text-emerald-500" /> ✨ 인터뷰 내용을 바탕으로 에코에게 추천받기</>
                            )}
                        </Button>

                        <div className="space-y-5">
                            <div>
                                <label className="flex items-center gap-2 text-sm font-bold text-slate-700 mb-2">
                                    <Palette className="h-4 w-4 text-emerald-500" />
                                    전체 분위기 및 컨셉 <span className="text-rose-500">*</span>
                                </label>
                                <input
                                    name="concept" value={formData.concept} onChange={handleInputChange}
                                    placeholder="예: 따뜻하고 부드러운 가을 느낌"
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:border-transparent transition-all"
                                />
                            </div>

                            <div>
                                <label className="flex items-center gap-2 text-sm font-bold text-slate-700 mb-2">
                                    <BookOpen className="h-4 w-4 text-amber-500" />
                                    앞면 디자인 요구사항
                                </label>
                                <textarea
                                    name="frontDesc" value={formData.frontDesc} onChange={handleInputChange}
                                    placeholder="예: 제목이 중앙에 여백을 두고 배치되었으면 좋겠어요."
                                    rows={2}
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-amber-500 transition-all"
                                />
                            </div>

                            <div>
                                <label className="flex items-center gap-2 text-sm font-bold text-slate-700 mb-2">
                                    <AlignLeft className="h-4 w-4 text-blue-500" />
                                    책등(Spine) 요구사항
                                </label>
                                <input
                                    name="spineDesc" value={formData.spineDesc} onChange={handleInputChange}
                                    placeholder="예: 깔끔한 고딕체로 세로 줄바꿈 없이."
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                                />
                            </div>

                            <div>
                                <label className="flex items-center gap-2 text-sm font-bold text-slate-700 mb-2">
                                    <LayoutTemplate className="h-4 w-4 text-rose-500" />
                                    뒷면 디자인 요구사항
                                </label>
                                <textarea
                                    name="backDesc" value={formData.backDesc} onChange={handleInputChange}
                                    placeholder="예: 독자에게 건네는 따뜻한 위로의 한마디."
                                    rows={2}
                                    className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-sm resize-none focus:outline-none focus:ring-2 focus:ring-rose-500 transition-all"
                                />
                            </div>

                            <Button
                                onClick={handleGenerate}
                                disabled={isGenerating || isImageLoading || !formData.concept}
                                className="w-full h-14 bg-slate-800 hover:bg-slate-900 text-white rounded-xl font-bold text-lg shadow-lg hover:shadow-xl transition-all mt-4"
                            >
                                {isGenerating || isImageLoading ? (
                                    <><Loader2 className="animate-spin mr-2 h-5 w-5" /> {isImageLoading ? 'AI 배경 그리는 중...' : '3D 렌더링 중...'}</>
                                ) : (
                                    <><PenTool className="mr-2 h-5 w-5" /> 에코에게 3D 디자인 맡기기</>
                                )}
                            </Button>
                        </div>
                    </div>

                    {designParams && (
                        <div className="bg-emerald-50 rounded-2xl p-5 border border-emerald-100 shadow-sm">
                            <h3 className="text-sm font-bold flex items-center gap-2 text-emerald-800 mb-2">
                                <Info className="h-4 w-4" /> 에코의 디자인 노트
                            </h3>
                            <p className="text-xs text-emerald-700 leading-relaxed font-medium break-keep">
                                작가님의 컨셉을 분석하여 <strong className="font-bold underline decoration-emerald-300 decoration-2 underline-offset-2">{style.layout}</strong> 레이아웃과 <strong className="font-bold underline decoration-emerald-300 decoration-2 underline-offset-2">{style.texture}</strong> 질감을 3D 표지에 매칭했습니다. 우측의 조명 아래서 이리저리 돌려보며 확인해 보세요.
                            </p>
                        </div>
                    )}

                    {/* Interactive Typography & Layout Controls */}
                    <div className="bg-white rounded-3xl p-6 shadow-xl shadow-emerald-900/5 border border-emerald-100 flex flex-col gap-5">
                        <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2">
                            <Type className="h-4 w-4 text-emerald-500" /> 서체 스타일
                        </h3>
                        <div className="grid grid-cols-3 gap-2">
                            <Button variant={fontStyle === 'serif' ? 'default' : 'outline'} onClick={() => setFontStyle('serif')} className={`h-12 font-serif text-[15px] ${fontStyle === 'serif' ? 'bg-emerald-600 hover:bg-emerald-700 text-white' : 'text-slate-600 hover:bg-slate-50'}`}>명조</Button>
                            <Button variant={fontStyle === 'sans' ? 'default' : 'outline'} onClick={() => setFontStyle('sans')} className={`h-12 font-sans font-medium text-[15px] ${fontStyle === 'sans' ? 'bg-emerald-600 hover:bg-emerald-700 text-white' : 'text-slate-600 hover:bg-slate-50'}`}>고딕</Button>
                            <Button variant={fontStyle === 'classic' ? 'default' : 'outline'} onClick={() => setFontStyle('classic')} className={`h-12 font-serif italic tracking-wider text-[15px] ${fontStyle === 'classic' ? 'bg-emerald-600 hover:bg-emerald-700 text-white' : 'text-slate-600 hover:bg-slate-50'}`}>클래식</Button>
                        </div>

                        <h3 className="text-sm font-bold text-slate-800 flex items-center gap-2 mt-2">
                            <LayoutTemplate className="h-4 w-4 text-emerald-500" /> 제목 위치
                        </h3>
                        <div className="grid grid-cols-3 gap-2">
                            <Button variant={textPosition === 'top' ? 'default' : 'outline'} onClick={() => setTextPosition('top')} className={`h-12 ${textPosition === 'top' ? 'bg-slate-800 text-white' : 'text-slate-600 hover:bg-slate-50'}`}><ArrowUpToLine className="h-5 w-5" /></Button>
                            <Button variant={textPosition === 'center' ? 'default' : 'outline'} onClick={() => setTextPosition('center')} className={`h-12 ${textPosition === 'center' ? 'bg-slate-800 text-white' : 'text-slate-600 hover:bg-slate-50'}`}><AlignVerticalJustifyCenter className="h-5 w-5" /></Button>
                            <Button variant={textPosition === 'bottom' ? 'default' : 'outline'} onClick={() => setTextPosition('bottom')} className={`h-12 ${textPosition === 'bottom' ? 'bg-slate-800 text-white' : 'text-slate-600 hover:bg-slate-50'}`}><ArrowDownToLine className="h-5 w-5" /></Button>
                        </div>
                    </div>
                </aside>

                {/* Right: 3D Viewer */}
                <div className="flex-1 min-h-[400px] sm:min-h-[500px] lg:h-[calc(100vh-140px)] bg-gradient-to-br from-slate-100 via-slate-50 to-slate-200 rounded-3xl relative overflow-hidden flex flex-col items-center border border-slate-200 shadow-inner">

                    {/* Scene / Perspective Container */}
                    <div className="flex-1 w-full flex items-center justify-center perspective-[2000px] overflow-visible">

                        {/* THE 3D BOOK */}
                        <div
                            className="relative w-[240px] h-[350px] sm:w-[340px] sm:h-[500px]"
                            style={{
                                transformStyle: 'preserve-3d',
                                transform: `translateZ(${translateZ}px) rotateX(${rotateX}deg) rotateY(${rotateY}deg) scale(${scale})`,
                                transition: 'transform 1s cubic-bezier(0.2, 0.8, 0.2, 1)'
                            }}
                        >
                            {/* FRONT FACE (Z = +25px) */}
                            <div
                                className="absolute top-0 left-0 w-full h-full rounded-r-lg rounded-l-[4px] shadow-2xl overflow-hidden"
                                style={{
                                    transform: 'translateZ(25px)',
                                    background: bgImageUrl ? `url(${bgImageUrl}) center/cover no-repeat` : `linear-gradient(135deg, ${colors.primary}, ${colors.secondary})`,
                                    backfaceVisibility: 'hidden'
                                }}
                            >
                                {/* Background darkening overlay for text readability if using image */}
                                {bgImageUrl && <div className="absolute inset-0 bg-black/40"></div>}

                                {/* Texture & Overlays */}
                                <div className="absolute inset-0 opacity-40 mix-blend-multiply" style={{ backgroundImage: textureUrl }}></div>
                                {/* Shine effect */}
                                <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-white/10 to-transparent mix-blend-overlay"></div>
                                {/* Spine groove shadow */}
                                <div className="absolute top-0 bottom-0 left-0 w-6 bg-gradient-to-r from-black/40 via-black/5 to-transparent mix-blend-overlay"></div>
                                <div className="absolute top-0 bottom-0 left-8 w-px bg-white/20 mix-blend-overlay"></div>

                                {/* Content */}
                                <div className={`absolute inset-0 p-10 flex flex-col z-10 ${textPosition === 'top' ? 'justify-start mt-8' : textPosition === 'bottom' ? 'justify-end mb-8' : 'justify-center'} ${style.layout === 'modern' ? 'items-start text-left' : 'items-center text-center'}`}>
                                    {style.layout === 'modern' && textPosition !== 'bottom' && <div className="w-8 h-1 mb-6" style={{ backgroundColor: colors.accent }}></div>}

                                    <div className={`${style.layout === 'classic' && textPosition !== 'top' ? 'mt-12' : ''} ${style.layout === 'elegant' ? 'border p-6 rounded-sm' : ''} w-full`} style={{ borderColor: `${colors.accent}40` }}>
                                        {style.layout === 'elegant' && <p className={`text-xs italic mb-6 opacity-80 ${fontStyle === 'sans' ? 'font-sans' : 'font-serif'}`} style={{ color: colors.textFront }}>Memoir Collection</p>}
                                        <h1 className={`text-4xl font-bold tracking-tight mb-4 break-keep leading-[1.2] ${fontStyle === 'sans' ? 'font-sans' : fontStyle === 'classic' ? 'font-serif italic tracking-[0.1em]' : 'font-serif'}`} style={{ color: colors.textFront }}>
                                            {currentProject.title}
                                        </h1>
                                        <p className={`text-sm tracking-widest uppercase opacity-80 break-keep ${fontStyle === 'sans' ? 'font-sans' : 'font-serif'}`} style={{ color: colors.accent }}>
                                            {generatedTexts.frontSubtitle}
                                        </p>
                                    </div>

                                    <div className={`${style.layout === 'modern' ? 'mt-8' : 'mt-12'}`}>
                                        {style.layout === 'classic' && <div className="w-12 h-[1px] mx-auto mb-6" style={{ backgroundColor: colors.accent }}></div>}
                                        <p className={`text-lg tracking-widest ${style.layout === 'modern' || fontStyle === 'sans' ? 'font-sans font-medium' : 'font-serif'}`} style={{ color: colors.textFront }}>
                                            {currentProject.author}
                                        </p>
                                    </div>
                                    {style.layout === 'modern' && textPosition === 'bottom' && <div className="w-8 h-1 mt-6" style={{ backgroundColor: colors.accent }}></div>}
                                </div>
                            </div>

                            {/* BACK FACE (rotateY 180, Z = +25px relative to back) */}
                            <div
                                className="absolute top-0 left-0 w-full h-full rounded-l-lg rounded-r-[4px] shadow-2xl overflow-hidden flex flex-col items-center justify-center p-12"
                                style={{
                                    transform: 'rotateY(180deg) translateZ(25px)',
                                    background: bgImageUrl ? `url(${bgImageUrl}) center/cover no-repeat` : colors.primary,
                                    backfaceVisibility: 'hidden'
                                }}
                            >
                                {/* Reverse flip the background if it's an image so it wraps continuously around the spine hypothetically */}
                                {bgImageUrl && <div className="absolute inset-0 bg-black/40" style={{ transform: 'scaleX(-1)' }}></div>}

                                <div className="absolute inset-0 opacity-40 mix-blend-multiply" style={{ backgroundImage: textureUrl }}></div>
                                {/* Shine effect */}
                                <div className="absolute inset-0 bg-gradient-to-bl from-transparent via-white/5 to-transparent mix-blend-overlay"></div>
                                {/* Spine groove shadow (reversed for back) */}
                                <div className="absolute top-0 bottom-0 right-0 w-6 bg-gradient-to-l from-black/40 via-black/5 to-transparent mix-blend-overlay"></div>

                                <div className="relative z-10 text-center flex flex-col items-center justify-between h-full py-8">
                                    <Sparkles className="mx-auto mb-8 opacity-60" style={{ color: colors.accent, width: 28, height: 28 }} />
                                    <p className="font-serif text-base leading-relaxed break-keep" style={{ color: colors.textFront }}>
                                        "{generatedTexts.backBlurb}"
                                    </p>
                                    <div className="mt-16 text-[10px] font-mono tracking-[0.2em] opacity-50" style={{ color: colors.textFront }}>
                                        PUBLISHED BY LEAFNOTE
                                    </div>
                                </div>
                            </div>

                            {/* SPINE (width 50px, rotateY -90, position left edge) */}
                            <div
                                className="absolute top-0 h-full overflow-hidden flex flex-col items-center justify-between py-12"
                                style={{
                                    width: '50px',
                                    left: '-25px', // Center on the left border (width/2)
                                    transform: 'rotateY(-90deg)',
                                    backgroundColor: colors.primary, // always solid
                                    boxShadow: 'inset 4px 0 10px rgba(0,0,0,0.5), inset -4px 0 10px rgba(255,255,255,0.1)'
                                }}
                            >
                                <div className="absolute inset-0 opacity-40 mix-blend-multiply" style={{ backgroundImage: textureUrl }}></div>
                                <div className="absolute inset-0 bg-gradient-to-r from-white/10 via-transparent to-black/20 mix-blend-overlay"></div>

                                <div className="relative z-10 text-xs font-mono font-bold tracking-widest uppercase origin-center transform rotate-90" style={{ color: colors.textSpine, opacity: 0.8 }}>
                                    {currentProject.author}
                                </div>

                                <div className="relative z-10 w-full flex-1 flex items-center justify-center mt-8 mb-8">
                                    <span className="font-serif text-[22px] font-bold tracking-[0.3em] whitespace-nowrap drop-shadow-sm" style={{ color: colors.textSpine, writingMode: 'vertical-rl', textOrientation: 'mixed' }}>
                                        {generatedTexts.spineTitle}
                                    </span>
                                </div>

                                <div className="relative z-10 w-4 h-4 rounded-full border-[2px]" style={{ borderColor: colors.accent }}></div>
                            </div>

                            {/* RIGHT PAGE EDGES (width 50, rotateY 90) */}
                            <div
                                className="absolute top-[3px] bottom-[3px] bg-[#fdfbf7] overflow-hidden"
                                style={{
                                    width: '46px',
                                    right: '-23px', // center on right edge
                                    transform: 'rotateY(90deg)',
                                    boxShadow: 'inset 0 0 20px rgba(0,0,0,0.1)'
                                }}
                            >
                                {/* simulated page lines */}
                                <div className="w-full h-full opacity-30" style={{ background: 'repeating-linear-gradient(to right, transparent, transparent 1px, #d1d5db 1px, #d1d5db 2px)' }}></div>
                            </div>

                            {/* TOP PAGE EDGES (X rot 90) */}
                            <div
                                className="absolute left-[3px] right-[3px] bg-[#fdfbf7] overflow-hidden"
                                style={{
                                    height: '46px', // inner depth
                                    top: '-23px', // center on top edge
                                    transform: 'rotateX(90deg)',
                                    boxShadow: 'inset 0 0 15px rgba(0,0,0,0.1)'
                                }}
                            >
                                <div className="w-full h-full opacity-30" style={{ background: 'repeating-linear-gradient(to bottom, transparent, transparent 1px, #d1d5db 1px, #d1d5db 2px)' }}></div>
                            </div>

                            {/* BOTTOM PAGE EDGES (X rot -90) */}
                            <div
                                className="absolute left-[3px] right-[3px] bg-[#e6e4df] overflow-hidden"
                                style={{
                                    height: '46px',
                                    bottom: '-23px',
                                    transform: 'rotateX(-90deg)',
                                    boxShadow: 'inset 0 0 15px rgba(0,0,0,0.2)'
                                }}
                            >
                                <div className="w-full h-full opacity-30" style={{ background: 'repeating-linear-gradient(to bottom, transparent, transparent 1px, #d1d5db 1px, #d1d5db 2px)' }}></div>
                            </div>

                        </div>
                    </div>

                    {/* 3D Controls */}
                    <div className="absolute bottom-4 sm:bottom-8 left-0 w-full flex justify-center gap-3 px-4 z-20">
                        <div className="bg-white/90 backdrop-blur-md p-1.5 sm:p-2 rounded-2xl shadow-xl border border-white/50 flex gap-0.5 sm:gap-1 isolate scale-90 sm:scale-100">
                            <Button
                                variant={viewAngle === 'perspective' ? 'default' : 'ghost'}
                                onClick={() => setViewAngle('perspective')}
                                className={viewAngle === 'perspective' ? 'bg-slate-800 text-white rounded-xl shadow-inner' : 'rounded-xl text-slate-600 hover:text-slate-900'}
                            >
                                <Rotate3d className="mr-2 h-4 w-4" /> 입체 뷰
                            </Button>
                            <div className="w-px bg-slate-200 my-2 mx-1"></div>
                            <Button variant={viewAngle === 'front' ? 'secondary' : 'ghost'} onClick={() => setViewAngle('front')} className={`rounded-xl font-bold ${viewAngle === 'front' ? 'bg-emerald-100 text-emerald-900' : 'text-slate-600'}`}>앞면</Button>
                            <Button variant={viewAngle === 'spine' ? 'secondary' : 'ghost'} onClick={() => setViewAngle('spine')} className={`rounded-xl font-bold ${viewAngle === 'spine' ? 'bg-emerald-100 text-emerald-900' : 'text-slate-600'}`}>책등</Button>
                            <Button variant={viewAngle === 'back' ? 'secondary' : 'ghost'} onClick={() => setViewAngle('back')} className={`rounded-xl font-bold ${viewAngle === 'back' ? 'bg-emerald-100 text-emerald-900' : 'text-slate-600'}`}>뒷면</Button>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
